### ISSUE TITLE
Adding two unreachable return statements causes garbage to be rendered

### ISSUE THREAD

**Issue by paulthomson** [mc-imperial/shader-compiler-bugs#37]
[[Shaders, screenshots, error log, reproduction steps, etc.]](https://github.com/mc-imperial/shader-compiler-bugs/tree/master/iphone-se-webgl/wrong_images/large-v100-webgl-e492c97b6266d2e3_inv_variant_27) [[ZIP]](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mc-imperial/shader-compiler-bugs/tree/master/iphone-se-webgl/wrong_images/large-v100-webgl-e492c97b6266d2e3_inv_variant_27)

Recipient:

![recipient image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/iphone-se-webgl/wrong_images/large-v100-webgl-e492c97b6266d2e3_inv_variant_27/recipient_reduced_final.png "recipient image")

Variant:

![variant image](https://github.com/mc-imperial/shader-compiler-bugs/raw/master/iphone-se-webgl/wrong_images/large-v100-webgl-e492c97b6266d2e3_inv_variant_27/variant_27_reduced_final_manual.png "variant image")

**Comment by paulthomson** [comment]
Reported:
https://community.imgtec.com/forums/topic/bug-glsl-iphone-se-unreachable-return-statements-in-shader-renders-garbage/

**Comment by paulthomson** [comment]
Also reported to Apple. Bug report ID: 29478780

**Comment by afd** [comment]
Fixed by Apple, and acknowledged here:

https://support.apple.com/en-us/HT207617

"
WebKit

Available for: iPhone 5 and later, iPad 4th generation and later, iPod touch 6th generation and later

Impact: Processing maliciously crafted web content may result in the disclosure of process memory

Description: An information disclosure issue existed in the processing of OpenGL shaders. This issue was addressed through improved memory management.

CVE-2017-2424: Paul Thomson (using the GLFuzz tool) of the Multicore Programming Group, Imperial College London
"
